### ISSUE TITLE
[Suggestion] Add an option to check if you want to pass loots that could not be needed or greeded;

### ISSUE THREAD

**Issue by imgidedin** [Iaotle/LootMaster#1]
Currently, we have to have a macro that does:

/need
/wait 1
/pass

If we could have it all in one go, would be great.

Something like this:
![image](https://user-images.githubusercontent.com/19570528/167438585-94dcf838-89c4-4a48-97b4-0095b64d70ce.png)

**Comment by imgidedin** [comment]
To add to this, could also have it automatically pass anything that doesnt meet the filter, to work with my other sugestion.

**Comment by Iaotle** [comment]
I don't really maintain this, I just revived it so it's still possible to use after it got archived. Feel free to make a pull request with these features.

**Comment by Iaotle** [comment]
Someone added this, please use that functionality :)
