### ISSUE TITLE
[Bug] Display roll information in chat not persistent.

### ISSUE THREAD

**Issue by imgidedin** [Iaotle/LootMaster#3]
If you un-check `Display roll information in chat`, it will revert back to checked on the next time you open the game.

**Comment by Iaotle** [comment]
I don't really maintain this, I just revived it so it's still possible to use after it got archived. Feel free to make a pull request with these features.

**Comment by xStarryNight** [comment]
This should be fixed already, if it isn't then let me know and I will look into it.
